[project]
name = "docurag-universal-document-intelligence-assistant"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "iamjahir09", email = "jahirshaikh162003@gmail.com" }
]
requires-python = ">=3.11"
dependencies = [
    "python-multipart>=0.0.32",
]

[project.scripts]
docurag-universal-document-intelligence-assistant = "docurag_universal_document_intelligence_assistant:main"

[build-system]
requires = ["uv_build>=0.12.10,<0.13.0"]
build-backend = "uv_build"
